### ISSUE TITLE
Feature request / Mobile friendly

### ISSUE THREAD

**Issue by Boukhtam** [softvenue/i18n#18]
Firstly I'd like to thank @Aissaoui-Ahmed for the new [feature ](https://softvenue.net/i18n/).
But there is some additions must be done:

1. Titling & Description (People needs to know what is it about)
2. Documentation (How to use)
3. We need to make it mobile friendly. 
4. Other 
      - Layouts
      - 404 page go to [softvenue.net/somthing_irrelevant](https://softvenue.net/i18n/somthing_irrelevant)
      - ETC

**Comment by Aissaoui-Ahmed** [comment]
thank you @Boukhtam 

I need designer to help and page 404 WIP
/cc @Salem-Abderaouf

**Comment by celyes** [comment]
i'll make it mobile friendly.
404 page should be designed by @Salem-Abderaouf first.

**Comment by celyes** [comment]
The website is mobile-friendly now and 404 page is up and running.
issue solved.
