### ISSUE TITLE
إستفسار

### ISSUE THREAD

**Issue by 3imed-jaberi** [softvenue/i18n#33]
<div dir="rtl"> 

هل اقوم بإضافة هذه الملفات او لا داعي لها : 
 - CHANGELOG.md
 - AUTHORS.md

**Comment by celyes** [comment]
يمكنك إضافة ملف AUTHORS.md 
حتى يعرف جميع من يهتم بالمشروع من هم المساهمون
اما بالنسبة لملف CHANGELOG.md 
فأرى انه لا داعي لإضافته كون طبيعة المشروع تجعل من الصعب تتبع التغييرات و تسجيلها على اساس يومي.

**Comment by Aissaoui-Ahmed** [comment]
عما قريب سأضيف لائحة المساهمين آلياً
