### ISSUE TITLE
 القائمة المنسدلة في الموقع لا تعمل على الموبايل و بعض المتصفحات القديمة

### ISSUE THREAD

**Issue by celyes** [softvenue/i18n#41]
**خلل في عنصر اساسي في الموقع**
القائمة المنسدلة في الموقع لا تعمل على الموبايل و بعض المتصفحات القديمة

**خطوات إعادة حدوث الخطأ**
1. قم بالذهاب إلى الحقل الخاص بالبحث عن الكلمات 
2. قم بكتابة كلمة او مصطلح ما
3. يتوقع ظهور القائمة المنسدلة و لكنها لا تظهر

**حل محتمل**
إجراء مراجعة شاملة لأكواد الجافاسكريبت و الـ سي أس أس الخاصة بالعرض

**Comment by Aissaoui-Ahmed** [comment]
هي تعمل بكل كفاءة 
جربتها في 

Condor P6+
chrome: 77.0.3865.73
OS: Android 6.0

>ملاحظة : قد يستغرق تحميل الصفحة وقتا

**Comment by 3imed-jaberi** [comment]
<div dir='rtl'>

هي تعمل بكل كفاءة 💯  ..
جربتها في :

</div> 

Phone : Huawei P8 Lite 2017
Browser: Chrome version 73.0.3683.75 
OS: Android 7.0
