### ISSUE TITLE
.اقتراح

### ISSUE THREAD

**Issue by celyes** [softvenue/i18n#42]
<div align="left">
نحن كمبرمجين نعلم أن الملفات ذات صيغة `yml` تستعمل كملفات لحفظ الإعدادات وليست لنقل البيانات
و نعلم أيضا أن هناك صيغة أخرى لنقل البيانات و هي `xml` 

و عليه أقترح تغيير صيغة ملف i18n.yml 
إلى i18n.xml.
</div>

**Comment by Aissaoui-Ahmed** [comment]
<div dir=rtl>
شكرا على إقتراحك @celyes 

سيتم العمل عليه عن قريب

**Comment by celyes** [comment]
جار إغلاق المشكلة لعدم الجدوى.
