### ISSUE TITLE
اقتراح

### ISSUE THREAD

**Issue by bibs2091** [softvenue/i18n#46]
<div dir="rtl">

يرجى الاضافة الى الوصف معلومة ' عدم تعديل ملف i18n.yml لانه يتم تعديله آليا'

**Comment by Aissaoui-Ahmed** [comment]
<div dir=rtl>

يمكنك فتح طلب تغيير PR ?

**Comment by celyes** [comment]
<div align="right">
يمكنك اضافة  الوصف من خلال فتح طلب تغيير كما وضح التعليق السابق
جارٍ إغلاق المشكلة.
</div>
