### ISSUE TITLE
اقتراح

### ISSUE THREAD

**Issue by atefBB** [softvenue/i18n#52]
<div dir="rtl">
أقترح استعمال القاموس التقني لمشروع آرابايز بصفته مرجعا لترجمة المصطلحات التقنية.
رابط القاموس من <a href="https://www.arabeyes.org/%D8%A7%D9%84%D9%82%D8%A7%D9%85%D9%88%D8%B3_%D8%A7%D9%84%D8%AA%D9%82%D9%86%D9%8A">هنا</a>.
وشكرا.
</div>

**Comment by Aissaoui-Ahmed** [comment]
مبادرة رائعة ❤️

**Comment by celyes** [comment]
سيتم أخذ الملاحظة بعين الاعتبار.
تم إغلاق المشكلة.

**Comment by atefBB** [comment]
<div dir="rtl">شكرا لكما.</div>
