### ISSUE TITLE
Pb !!

### ISSUE THREAD

**Issue by 3imed-jaberi** [softvenue/i18n#56]
<div dir='rtl'>
لدينا ملف i18n.yml في المشروع و لدينا أيضا انه يتم تجاهله في المشروع ... !!!!

**Comment by Aissaoui-Ahmed** [comment]
يتم إنشائه اوتوماتيكيا

**Comment by celyes** [comment]
يتم توليد الملف تلقائيا.

**Comment by 3imed-jaberi** [comment]
@celyes, يجب اصلاح هذا ..

**Comment by 3imed-jaberi** [comment]
<div dir='rtl'>
هناك منهجين يجب اتباع احدهما : 

1- يجب حذف اسم هذا الملف من .gitignore .. 
2- يجب حذف هذا الملف من المشروع و الابقاء على الاسم في .gitignore 

🤠

@softvenue/i18n

**Comment by celyes** [comment]
ما دام انها تعمل لا اظن ان لأي من الحلين ضرورة ولكن اذا كنت مصرا فيستحسن حذف اسم الملف من 
الـ .gitignore

**Comment by 3imed-jaberi** [comment]
> ما دام انها تعمل لا اظن ان لأي من الحلين ضرورة ولكن اذا كنت مصرا فيستحسن حذف اسم الملف من
> الـ .gitignore

<div dir='rtl'>
كيف ليس ضروري الحاليين .. هناك علة !! 🤯

**Comment by Aissaoui-Ahmed** [comment]
<div dir=rtl>
كيف يعمل؟<br>
أولا يتم إنشاء الملف YML إستنادا على JSON وتجنبا للإعادة يتم تجاهله في .gitignore في بعض الحالات يقع مشكل ظهور ملف YML والحل هو : <br>
1- حذف الملف <br>
2- حفظ التغييرات مع force--

**Comment by celyes** [comment]
تم توضيح الأمر و حل المشكلة.
