### ISSUE TITLE
انشاء قواعد الترجمة

### ISSUE THREAD

**Issue by aissat** [softvenue/i18n#77]
السلام عليكم 
لدي بعض اقتراح حسب وجهة نظري من مهم العمل عليه قبل بداية العمل على ترجمة الكلمات هو :
**العمل على انشاء و وضع اسس وقواعد الترجمة** 
لان العمل على هذا النقطة  راح يظبط الترجمة و كيفية التعامل مع الكلمات 
مثلا لو اخذنا مثال في #76 صراحة لايوجد اي مصطلح عربي اصيل لكلمة  backend  لذلك سيكون امامنا الكثير من اقترحات ف بدون قواعد تظبط ترجمة على اي اساس نختار الترجمة الادق والاقرب للمعنى 
في اخير اضن ان العمل على وضع قواعد و اسس قياسية عمل كبير و راح  يفيد المحتوى العربي اكثر بحيث يكون مرجع موحد لكل مشاريع الترجمة 
@softvenue/all

**Comment by celyes** [comment]
يبدو اقتراحاً جيداُ
سأبحث عن مصادر لاساسيات وضع المصطلحات من الناحية اللغوية و أوافيكم بها هنا حتى نكون على قدر المهمة.
شكرا لك
